name: "ci: Check Syntax"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "docs/**"
      - "files/**"
      - "shells/**"
env:
  NIX_SHOW_STATS: 1
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check Syntax
        run: nix flake check . --keep-going
